/**
 * Represents the collection of DOM elements generated by
 * the pagination engine from the report components on the current page.
 */
export interface SectionComponents {
    /**
     * The HTML element that serves as the header for the entire section.
     * `null` if the section has no section header.
     */
    sectionHeader: HTMLElement | null;

    /**
     * The HTML element that serves as the footer for the entire section.
     * `null` if the section has no section footer.
     */
    sectionFooter: HTMLElement | null;

    /**
     * The HTML element that serves as the header for this page.
     * `null` if the page has no header.
     */
    pageHeader: HTMLElement | null;

    /**
     * The HTML element that serves as the footer for this page.
     * `null` if the page has no footer.
     */
    pageFooter: HTMLElement | null;

    /**
     * The main HTML element for the this page content
     * This property is always defined.
     */
    pageContent: HTMLElement;
}

function cloneElement<T extends HTMLElement | null>(element?: T): T {
    return (element?.cloneNode(true) ?? null) as T;
}

export function cloneComponents(
    components: SectionComponents
): SectionComponents {
    return {
        sectionHeader: cloneElement(components.sectionHeader),
        sectionFooter: cloneElement(components.sectionFooter),
        pageHeader: cloneElement(components.pageHeader),
        pageFooter: cloneElement(components.pageFooter),
        pageContent: cloneElement(components.pageContent),
    };
}
