packages:
  - packages/*
  - examples/*
  - website
  - utils/*
  - tests/*

catalog:
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@vitest/coverage-v8': ^4.1.4
  esbuild: 0.28.0
  preact: ^10.27.2
  react: ^19.2.5
  react-dom: ^19.2.5
  typescript: ^6.0.2
  vite: ^8.0.8
  vitest: ^4.1.4

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - puppeteer

overrides:
  serialize-javascript@<7.0.5: '>=7.0.5'
  serialize-javascript@<=7.0.2: '>=7.0.3'
