/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MewoCompanyRouteImport } from './routes/mewo-company'
import { Route as IndexRouteImport } from './routes/index'

const MewoCompanyRoute = MewoCompanyRouteImport.update({
  id: '/mewo-company',
  path: '/mewo-company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mewo-company': typeof MewoCompanyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mewo-company': typeof MewoCompanyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mewo-company': typeof MewoCompanyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mewo-company'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mewo-company'
  id: '__root__' | '/' | '/mewo-company'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MewoCompanyRoute: typeof MewoCompanyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mewo-company': {
      id: '/mewo-company'
      path: '/mewo-company'
      fullPath: '/mewo-company'
      preLoaderRoute: typeof MewoCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MewoCompanyRoute: MewoCompanyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
