import { MarkdownPageEvent } from 'typedoc-plugin-markdown';

/**
 * @param {import("typedoc-plugin-markdown").MarkdownApplication} app
 */
export function load(app) {
    app.renderer.on(
        MarkdownPageEvent.BEGIN,
        /** @param {import('typedoc-plugin-markdown').MarkdownPageEvent} page */
        (page) => {
            page.frontmatter = {
                title: page.model.name,
                sidebar_position: 99,
            };
        }
    );

    app.renderer.on(
        MarkdownPageEvent.END,
        /** @param {import('typedoc-plugin-markdown').MarkdownPageEvent} page */
        (page) => {
            page.contents = page.contents
                .replace(
                    /(?<=---.*)(---)/s,
                    '---\n<!-- Code generated by TypeDoc. DO NOT EDIT -->'
                )
                .replaceAll('](core.md', '](/core/api.md')
                .replaceAll('](vanilla.md', '](/vanilla/api.md')
                .replaceAll('](vanilla.md', '](/vanilla/api.md')
                .replaceAll('](puppeteer.md', '](/puppeteer/api.md');
        }
    );
}
