name: PR

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm -r -F @paprize/snapshot-tests exec playwright install --with-deps

      - name: Run Tests
        run: pnpm run test

      - name: Run Coverage
        run: pnpm run coverage

      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: tests/snapshot/playwright-report/
          retention-days: 30
